server:
  port: 9003
#spring:
#  rabbitmq:
#    host: docker-pool.localdomain
#    port: 5673
#    username: user
orders:
  queue:
    host: docker-pool.localdomain
    port: 5673
    passwd: pass
    user: user
    queue-name: orderqueue
#    password: pass