server:
  port: 9003
orders:
  queue:
    host: ${QHOST:docker-pool.localdomain}
    port: ${QPORT:5672}
    passwd: ${QPASSWD:pass}
    user: ${QUSR:user}
    queue-name: ${QNAME:orderqueue}
app:
  cors: ${CORS_ORIGIN:*}